import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "@/app/Components/Navbar";
import Footer from "./Components/Footer";
import FloatingIcons from "./FloatingIcons";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.variable} bg-gray-900 text-gray-100 antialiased font-sans`}
      >
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <FloatingIcons />
        </div>

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
